### PR TITLE
Add abort command

### PR DESCRIPTION
**Pull request by dschwen**
This adds a command to abort the current make process. I have not added a default keybinding for this (it is an advanced and (hopefully) infrequently used functionality, so people can add it themselves if they need it or simply run it from the command palette).

### CODE REVIEW

**Comment by dschwen** [comment]
Hey @fiveisprime, thanks for adding me to the repo! I'm not supposed to merge my own PRs, though, right? I'd appreciate a second pair of eyeballs on them :-)

Also there is no way to currently share the apm maintainership, is there?

**Comment by fiveisprime** [comment]
I'll still take a look, but I need a few before I get to it. I believe apm just uses the repo - the "publish" step simply creates a tag and pushes to the repo. It's worth trying it since you have push access. :)

**Comment by dschwen** [comment]
Something is still fishe here. Let me look into it...

**Comment by dschwen** [comment]
Nope, it's all good as far as I can see (some dev commits broke my branch unrelated to this PR)

**Pull request merged**
