### PR TITLE
Target selector

### PR DESCRIPTION
**Pull request by dschwen**
Adds a target selector to choose a valid make target:

image

This runs make and obtains a list of valid targets. It supports arbitrarily complex makefiles (e.g. include directives that generate targets and variable targets).

Replaces #35 

**I'm putting this out here for comments. There is a little more work to do to correctly deal with abort and running make while the target list is obtained**

### CODE REVIEW

**Comment by dschwen** [comment]
Whatever happened to this PR...

**Comment by fiveisprime** [comment]
I never merged it because it was marked as wip 🤣

Are you ready for it? I'm going to have to figure out how to publish this too.

**Comment by dschwen** [comment]
Let me see if this still rebases cleanly and rethink what I meant by "There is a little more work to do to correctly deal with abort and running make while the target list is obtained". Good to see you're still around :-)

**Comment by fiveisprime** [comment]
Sounds good and of course! I'm working on a competing product, but definitely keeping this alive. :)

**Comment by dschwen** [comment]
Ok, this PR seems fine. What's the competing product?

**Comment by fiveisprime** [comment]
And it's published! Fun fact: `apm` uses the repository field in `package.json` to publish the tag and if it doesn't like that format, you get a misleading error. 😅

Let me know if you'd ever like to dig into the extension API in VS Code. The getting started [docs](https://code.visualstudio.com/api/get-started/your-first-extension) are quite good. 😊

**Pull request merged**
